---
- name: Créer le dossier de configuration WireGuard
  file:
    path: /etc/wireguard
    state: directory
    mode: '0700'

- name: Générer une clé privée WireGuard si absente
  command: wg genkey
  register: wg_private_key
  no_log: true
  args:
    creates: /etc/wireguard/privatekey

- name: Sauvegarder la clé privée dans un fichier
  copy:
    dest: /etc/wireguard/privatekey
    content: "{{ wg_private_key.stdout }}"
    mode: '0600'
  when: wg_private_key.changed

- name: Lire la clé privée existante
  slurp:
    src: /etc/wireguard/privatekey
  register: wg_private_key_file

- name: Définir la clé privée dans une variable Ansible
  set_fact:
    wireguard_private_key: "{{ wg_private_key_file.content | b64decode | trim }}"
  no_log: true

- name: Définir l'adresse IP WireGuard du serveur
  set_fact:
    wireguard_server_address: "{{ wireguard_subnet | regex_replace('\\.[0-9]+/[0-9]+$', '.1/24') }}"

- name: Générer la configuration serveur wg0.conf
  template:
    src: wg0.conf.j2
    dest: "/etc/wireguard/{{ wireguard_interface }}.conf"
    owner: root
    group: root
    mode: '0600'

- name: Activer et démarrer le service WireGuard
  systemd:
    name: "wg-quick@{{ wireguard_interface }}"
    enabled: yes
    state: started
    daemon_reload: yes
