---

- name: Définir l’URL du fichier de tuning réseau selon OS
  set_fact:
    wireguard_sysctl_optimize_url: "https://github.com/hwdsl2/vpn-extras/releases/download/v1.0.0/sysctl-wg-ubuntu"


- name: Activer l’IP forwarding IPv4
  copy:
    dest: /etc/sysctl.d/99-wireguard-forward.conf
    content: |
      net.ipv4.ip_forward=1
      {% if wireguard_enable_ipv6 %}
            net.ipv6.conf.all.forwarding=1
      {% endif %}
    owner: root
    group: root
    mode: '0644'

- name: Télécharger le fichier sysctl distant pour optimisation réseau
  get_url:
    url: "{{ wireguard_sysctl_optimize_url }}"
    dest: /etc/sysctl.d/99-wireguard-optimize.conf
    mode: '0644'
  register: sysctl_download


- name: Charger le module tcp_bbr
  modprobe:
    name: tcp_bbr
  register: wireguard_supports_bbr

- name: Ajouter bbr/fq dans le fichier sysctl s’ils sont supportés
  blockinfile:
    path: /etc/sysctl.d/99-wireguard-optimize.conf
    block: |
      net.core.default_qdisc = fq
      net.ipv4.tcp_congestion_control = bbr
  when: wireguard_supports_bbr.changed


- name: Appliquer les paramètres sysctl immédiatement
  command: sysctl -p /etc/sysctl.d/99-wireguard-forward.conf
  changed_when: true


- name: Appliquer les optimisations réseau sysctl
  command: sysctl -p /etc/sysctl.d/99-wireguard-optimize.conf
  changed_when: true
